# src/config/development.yaml
server:
  port: 3000

db:
  postgres:
    host: localhost
    port: 5432
    username: root
    password: postgres
    database: postgres

redis:
  host: localhost
  port: 1234

mail:
  auth:
    user: developthug@gmail.com
    pass: testtest
